classdef KernelRegistry
    % Declarative registry of kernel definitions

    methods (Static)

        function registry = getRegistry()

            registry = struct();

            % =========================================================
            % Heat kernel (diffusion / low-pass)
            % =========================================================
            registry.Heat = struct( ...
                'Name', 'Heat', ...
                'NumParams', 1, ...
                'ParamNames', {{'tau'}}, ...
                'EquationLatex', '$$g(\lambda)=e^{-\tau \lambda}$$', ...
                'DefaultParams', @(axis) struct( ...
                    'tau', 1 / range(axis) ), ...
                'ParamRanges', @(axis) struct( ...
                    'tau', [0.1/range(axis), 10/range(axis)] ), ...
                'Function', @(p) @(lambda) exp(-p.tau .* lambda) ...
            );

            % =========================================================
            % Gaussian (radial spectral weighting)
            % =========================================================
            registry.Gaussian = struct( ...
                'Name', 'Gaussian', ...
                'NumParams', 2, ...
                'ParamNames', {{'sigma','mu'}}, ...
                'EquationLatex', ...
                    '$$g(\lambda)=\exp\!\left(-\frac{(\lambda-\mu)^2}{2\sigma^2}\right)$$', ...
                'DefaultParams', @(axis) struct( ...
                    'sigma', 0.1 * range(axis), ...
                    'mu', mean(axis) ), ...
                'ParamRanges', @(axis) struct( ...
                    'sigma', [0.02*range(axis), 0.5*range(axis)], ...
                    'mu', [min(axis), max(axis)] ), ...
                'Function', @(p) @(lambda) ...
                    exp(-(lambda-p.mu).^2 ./ (2*p.sigma^2)) ...
            );

            % =========================================================
            % Ricker / Classical Mexican Hat (NOT Laplacian-native)
            % =========================================================
            registry.Ricker = struct( ...
                'Name', 'Ricker (Classical Mexican Hat)', ...
                'NumParams', 1, ...
                'ParamNames', {{'sigma'}}, ...
                'EquationLatex', ...
                    ['$$g(\lambda)=\left(1-\frac{\lambda^2}{\sigma^2}\right)' ...
                     '\exp\!\left(-\frac{\lambda^2}{2\sigma^2}\right)$$'], ...
                'DefaultParams', @(axis) struct( ...
                    'sigma', 0.1 * range(axis) ), ...
                'ParamRanges', @(axis) struct( ...
                    'sigma', [0.02*range(axis), 0.5*range(axis)] ), ...
                'Function', @(p) @(lambda) ...
                    (1 - (lambda.^2 ./ p.sigma^2)) .* ...
                    exp(-lambda.^2 ./ (2*p.sigma^2)) ...
            );

            % =========================================================
            % Spectral Mexican Hat (GSP / Laplacian-native)
            %   g(λ) = λ exp(-τ λ)
            % =========================================================
            registry.SpectralMexicanHat = struct( ...
                'Name', 'Spectral Mexican Hat (GSP)', ...
                'NumParams', 1, ...
                'ParamNames', {{'tau'}}, ...
                'EquationLatex', ...
                    '$$g(\lambda)=\lambda\,e^{-\tau \lambda}$$', ...
                'DefaultParams', @(axis) struct( ...
                    'tau', 1 / range(axis) ), ...
                'ParamRanges', @(axis) struct( ...
                    'tau', [0.1/range(axis), 10/range(axis)] ), ...
                'Function', @(p) @(lambda) ...
                    lambda .* exp(-p.tau .* lambda) ...
            );

            % =========================================================
            % Difference of Gaussians (DoG) – optional but recommended
            % =========================================================
            registry.DoG = struct( ...
                'Name', 'Difference of Gaussians', ...
                'NumParams', 2, ...
                'ParamNames', {{'tau1','tau2'}}, ...
                'EquationLatex', ...
                    '$$g(\lambda)=e^{-\tau_1 \lambda}-e^{-\tau_2 \lambda}$$', ...
                'DefaultParams', @(axis) struct( ...
                    'tau1', 1 / range(axis), ...
                    'tau2', 5 / range(axis) ), ...
                'ParamRanges', @(axis) struct( ...
                    'tau1', [0.1/range(axis), 5/range(axis)], ...
                    'tau2', [1/range(axis), 20/range(axis)] ), ...
                'Function', @(p) @(lambda) ...
                    exp(-p.tau1 .* lambda) - exp(-p.tau2 .* lambda) ...
            );

        end
    end
end
