classdef SignalRegistry
    methods (Static)
        function reg = getRegistry()

            reg = struct();

            reg.Delta = struct( ...
                'Name','Delta', ...
                'NumParams',0, ...
                'ParamNames',{{}}, ...
                'DefaultParams',struct(), ...
                'Constructor',@()DeltaSignal() ...
            );

            reg.Noise = struct( ...
                'Name','Noise', ...
                'NumParams',2, ...
                'ParamNames',{{'sigma','mean'}}, ...
                'DefaultParams',struct('sigma',1,'mean',0), ...
                'Constructor',@()NoiseSignal() ...
            );

            reg.Patch = struct( ...
                'Name','Patch', ...
                'NumParams',1, ...
                'ParamNames',{{'radius'}}, ...
                'DefaultParams',struct('radius',5), ...
                'Constructor',@()PatchSignal() ...
            );
        end
    end
end
