function createComponentTemplate(name)
% Create scaffolding for a new UI component following web/ structure

base = fullfile(pwd, "components", "@" + name);
if ~exist(base, "dir")
    mkdir(base);
end

% Create web/ directory structure
webDir = fullfile(base, "web");
vendorDir = fullfile(webDir, "vendor");
if ~exist(webDir, "dir")
    mkdir(webDir);
end
if ~exist(vendorDir, "dir")
    mkdir(vendorDir);
end

% Files to create
files = struct();
files.m = fullfile(base, name + ".m");
files.readme = fullfile(base, "README.md");
files.html = fullfile(webDir, "index.html");
files.css = fullfile(webDir, "styles.css");
files.mainjs = fullfile(webDir, "main.js");
files.renderjs = fullfile(webDir, "render.js");

% Boilerplate contents
template.m = [
"classdef " + name + " < matlab.ui.componentcontainer.ComponentContainer\n" + ...
"    properties\n" + ...
"        Value\n" + ...
"    end\n\n" + ...
"    properties (Access = private, Transient, NonCopyable)\n" + ...
"        HTMLComponent matlab.ui.control.HTML\n" + ...
"    end\n\n" + ...
"    methods (Access = protected)\n" + ...
"        function setup(comp)\n" + ...
"            % If using default size, fill the parent container\n" + ...
"            if comp.Position(3) == 100 && comp.Position(4) == 100\n" + ...
"                parentPos = comp.Parent.Position;\n" + ...
"                comp.Position = [10 10 parentPos(3)-20 parentPos(4)-20];\n" + ...
"            end\n\n" + ...
"            comp.HTMLComponent = uihtml(comp);\n" + ...
"            comp.HTMLComponent.Position = [1 1 comp.Position(3:4)];\n" + ...
"            comp.HTMLComponent.HTMLSource = " + name + ".resolveHTMLSource();\n" + ...
"            comp.HTMLComponent.HTMLEventReceivedFcn = @(src, evt) comp.handleEvent(evt);\n" + ...
"            comp.update();\n" + ...
"        end\n\n" + ...
"        function update(comp)\n" + ...
"            if isempty(comp.HTMLComponent) || ~isvalid(comp.HTMLComponent)\n" + ...
"                return;\n" + ...
"            end\n" + ...
"            comp.HTMLComponent.Position = [1 1 comp.Position(3:4)];\n" + ...
"            comp.HTMLComponent.Data = struct('value', comp.Value);\n" + ...
"        end\n\n" + ...
"        function handleEvent(comp, evt)\n" + ...
"            disp(evt.HTMLEventName);\n" + ...
"        end\n" + ...
"    end\n\n" + ...
"    methods (Access = private, Static)\n" + ...
"        function htmlPath = resolveHTMLSource()\n" + ...
"            % Resolve the absolute path to web/index.html\n" + ...
"            classFile = mfilename('fullpath');\n" + ...
"            classDir = fileparts(classFile);\n" + ...
"            htmlPath = fullfile(classDir, 'web', 'index.html');\n" + ...
"        end\n" + ...
"    end\n" + ...
"end\n"
];

template.readme = [
"# " + name + " Component\n\n" + ...
"## Description\n" + ...
"[Component description]\n\n" + ...
"## Dependencies\n" + ...
"- D3.js version: [specify version]\n\n" + ...
"## Usage\n" + ...
"```matlab\n" + ...
"comp = " + name + "(uifigure);\n" + ...
"```\n"
];

template.html = [
"<!DOCTYPE html>\n<html>\n<head>\n" + ...
"  <meta charset='UTF-8'>\n" + ...
"  <title>" + name + "</title>\n" + ...
"  <link rel='stylesheet' href='styles.css'>\n" + ...
"</head>\n<body>\n" + ...
"  <div id='root'></div>\n" + ...
"</body>\n\n" + ...
"<!-- Load dependencies from vendor/ -->\n" + ...
"<script src='vendor/d3.v5.9.2.min.js'></script>\n\n" + ...
"<!-- Load component files -->\n" + ...
"<script src='render.js'></script>\n" + ...
"<script src='main.js'></script>\n\n" + ...
"<script>\n" + ...
"    // Validate dependencies loaded\n" + ...
"    if (typeof d3 === 'undefined') {\n" + ...
"        console.error('[" + name + "] D3.js failed to load');\n" + ...
"    }\n" + ...
"</script>\n" + ...
"</html>\n"
];

template.css = [
"/* Component-specific styling for " + name + " */\n" + ...
"html, body {\n" + ...
"    margin: 0;\n" + ...
"    padding: 0;\n" + ...
"    width: 100%;\n" + ...
"    height: 100%;\n" + ...
"    overflow: hidden;\n" + ...
"}\n\n" + ...
"#root {\n" + ...
"    width: 100%;\n" + ...
"    height: 100%;\n" + ...
"}\n"
];

template.mainjs = [
"/* Bootstrap logic for " + name + " component */\n\n" + ...
"function setup(htmlComponent) {\n" + ...
"    console.log('[" + name + "] setup() called');\n" + ...
"    \n" + ...
"    try {\n" + ...
"        var data = htmlComponent.Data;\n" + ...
"        renderComponent(data, htmlComponent);\n" + ...
"        \n" + ...
"        htmlComponent.addEventListener('DataChanged', function(event) {\n" + ...
"            console.log('[" + name + "] DataChanged event received');\n" + ...
"            renderComponent(htmlComponent.Data, htmlComponent);\n" + ...
"        });\n" + ...
"        \n" + ...
"        console.log('[" + name + "] Setup complete');\n" + ...
"    } catch (error) {\n" + ...
"        console.error('[" + name + "] Error in setup():', error);\n" + ...
"    }\n" + ...
"}\n\n" + ...
"console.log('[" + name + "] Controller loaded');\n"
];

template.renderjs = [
"/* Rendering logic for " + name + " component */\n\n" + ...
"function renderComponent(data, htmlComponent) {\n" + ...
"    console.log('[" + name + "] renderComponent() called with data:', data);\n" + ...
"    \n" + ...
"    // Clear previous content\n" + ...
"    d3.select('#root').selectAll('*').remove();\n" + ...
"    \n" + ...
"    // Add your D3 visualization here\n" + ...
"    var svg = d3.select('#root')\n" + ...
"        .append('svg')\n" + ...
"        .attr('width', '100%')\n" + ...
"        .attr('height', '100%');\n" + ...
"    \n" + ...
"    svg.append('text')\n" + ...
"        .attr('x', '50%')\n" + ...
"        .attr('y', '50%')\n" + ...
"        .attr('text-anchor', 'middle')\n" + ...
"        .text('" + name + " Component');\n" + ...
"}\n\n" + ...
"console.log('[" + name + "] Renderer loaded');\n"
];

% Write all files
writeFile(files.m, template.m);
writeFile(files.readme, template.readme);
writeFile(files.html, template.html);
writeFile(files.css, template.css);
writeFile(files.mainjs, template.mainjs);
writeFile(files.renderjs, template.renderjs);

disp("Template created for component: " + name);
disp("Structure:");
disp("  @" + name + "/");
disp("    ├── " + name + ".m");
disp("    ├── README.md");
disp("    └── web/");
disp("        ├── index.html");
disp("        ├── main.js");
disp("        ├── render.js");
disp("        ├── styles.css");
disp("        └── vendor/  (add dependencies here)");
end

function writeFile(filepath, content)
    fid = fopen(filepath, 'w');
    fwrite(fid, content);
    fclose(fid);
end