function createComponentTemplate(name, varargin)
% Create scaffolding for a new UI component or view
%
% Syntax:
%   createComponentTemplate(name)
%   createComponentTemplate(name, 'library', libraryType)
%   createComponentTemplate(name, 'library', libraryType, 'type', componentType)
%   createComponentTemplate(name, 'library', libraryType, 'type', componentType, 'testData', dataPath)
%
% Arguments:
%   name - Component name (string)
%   'library' - 'observable-plot' (default), 'd3', or 'custom'
%   'type' - 'view' (one-way) or 'component' (bidirectional, default: 'component')
%   'testData' - Optional path to test data file (e.g., '../data/faithful.tsv')
%
% Examples:
%   createComponentTemplate("MyChart", "library", "observable-plot", "type", "view")
%   createComponentTemplate("MyBrush", "library", "d3", "type", "component")
%   createComponentTemplate("MyPlot", "library", "observable-plot", "type", "view", "testData", "../data/faithful.tsv")

% Parse input arguments
p = inputParser;
addRequired(p, 'name', @isstring);
addParameter(p, 'library', 'observable-plot', @isstring);
addParameter(p, 'type', 'component', @isstring);
addParameter(p, 'testData', '', @isstring);
parse(p, name, varargin{:});

libraryType = p.Results.library;
componentType = p.Results.type;
testDataPath = p.Results.testData;

% Determine if this is a view or component
isView = strcmpi(componentType, 'view');

% Determine base directory
if isView
    baseDir = fullfile(pwd, "views");
else
    baseDir = fullfile(pwd, "controllers");
end

base = fullfile(baseDir, "@" + name);
if ~exist(base, "dir")
    mkdir(base);
end

% Create web/ directory structure
webDir = fullfile(base, "web");
vendorDir = fullfile(webDir, "vendor");
if ~exist(webDir, "dir")
    mkdir(webDir);
end
if ~exist(vendorDir, "dir")
    mkdir(vendorDir);
end


% Switch based on library type
switch lower(libraryType)
    case 'observable-plot'
        createObservablePlotComponent(name, base, webDir, vendorDir, isView);
        
    case 'd3'
        createD3Component(name, base, webDir, vendorDir, isView);
        
    otherwise
        % Use original custom template
        createCustomComponent(name, base, webDir, vendorDir, isView);
end

% Generate test files if requested
if ~isempty(testDataPath)
    generateTestFiles(name, libraryType, isView, testDataPath);
end

% Display success message
if isView
    typeStr = "view";
    dataFlowStr = "one-way data flow";
    dirStr = "views";
else
    typeStr = "component";
    dataFlowStr = "bidirectional with events";
    dirStr = "controllers";
end

disp("Template created:");
disp("  Name: " + name);
disp("  Type: " + typeStr + " (" + dataFlowStr + ")");
disp("  Library: " + libraryType);
if ~isempty(testDataPath)
    disp("  Test data: " + testDataPath);
end
disp("");
disp("Structure:");
disp("  " + dirStr + "/@" + name + "/");
disp("    ├── " + name + ".m");
disp("    ├── README.md");
disp("    └── web/");
disp("        ├── index.html");
disp("        ├── main.js");
disp("        ├── render.js");
disp("        ├── styles.css");
disp("        └── vendor/");
if strcmpi(libraryType, 'observable-plot')
    disp("            ├── d3.min.js");
    disp("            └── plot.min.js");
elseif strcmpi(libraryType, 'd3')
    disp("            └── d3.v5.9.2.min.js");
end

if ~isempty(testDataPath)
    disp("");
    disp("Test files:");
    disp("  tests/html/test_" + name + ".html");
    disp("  tests/matlab/test_" + name + ".m");
end
end

function createCustomComponent(name, base, webDir, ~, ~)
% Create custom component using original template logic
% Files to create
files = struct();
files.m = fullfile(base, name + ".m");
files.readme = fullfile(base, "README.md");
files.html = fullfile(webDir, "index.html");
files.css = fullfile(webDir, "styles.css");
files.mainjs = fullfile(webDir, "main.js");
files.renderjs = fullfile(webDir, "render.js");

% Boilerplate contents
template.m = [
"classdef " + name + " < matlab.ui.componentcontainer.ComponentContainer\n" + ...
"    properties\n" + ...
"        Value\n" + ...
"    end\n\n" + ...
"    properties (Access = private, Transient, NonCopyable)\n" + ...
"        HTMLComponent matlab.ui.control.HTML\n" + ...
"    end\n\n" + ...
"    methods (Access = protected)\n" + ...
"        function setup(comp)\n" + ...
"            % If using default size, fill the parent container\n" + ...
"            if comp.Position(3) == 100 && comp.Position(4) == 100\n" + ...
"                parentPos = comp.Parent.Position;\n" + ...
"                comp.Position = [10 10 parentPos(3)-20 parentPos(4)-20];\n" + ...
"            end\n\n" + ...
"            comp.HTMLComponent = uihtml(comp);\n" + ...
"            comp.HTMLComponent.Position = [1 1 comp.Position(3:4)];\n" + ...
"            comp.HTMLComponent.HTMLSource = " + name + ".resolveHTMLSource();\n" + ...
"            comp.HTMLComponent.HTMLEventReceivedFcn = @(src, evt) comp.handleEvent(evt);\n" + ...
"            comp.update();\n" + ...
"        end\n\n" + ...
"        function update(comp)\n" + ...
"            if isempty(comp.HTMLComponent) || ~isvalid(comp.HTMLComponent)\n" + ...
"                return;\n" + ...
"            end\n" + ...
"            comp.HTMLComponent.Position = [1 1 comp.Position(3:4)];\n" + ...
"            comp.HTMLComponent.Data = struct('value', comp.Value);\n" + ...
"        end\n\n" + ...
"        function handleEvent(comp, evt)\n" + ...
"            disp(evt.HTMLEventName);\n" + ...
"        end\n" + ...
"    end\n\n" + ...
"    methods (Access = private, Static)\n" + ...
"        function htmlPath = resolveHTMLSource()\n" + ...
"            % Resolve the absolute path to web/index.html\n" + ...
"            classFile = mfilename('fullpath');\n" + ...
"            classDir = fileparts(classFile);\n" + ...
"            htmlPath = fullfile(classDir, 'web', 'index.html');\n" + ...
"        end\n" + ...
"    end\n" + ...
"end\n"
];

template.readme = [
"# " + name + " Component\n\n" + ...
"## Description\n" + ...
"[Component description]\n\n" + ...
"## Dependencies\n" + ...
"- D3.js version: [specify version]\n\n" + ...
"## Usage\n" + ...
"```matlab\n" + ...
"comp = " + name + "(uifigure);\n" + ...
"```\n"
];

template.html = [
"<!DOCTYPE html>\n<html>\n<head>\n" + ...
"  <meta charset='UTF-8'>\n" + ...
"  <title>" + name + "</title>\n" + ...
"  <link rel='stylesheet' href='styles.css'>\n" + ...
"</head>\n<body>\n" + ...
"  <div id='root'></div>\n" + ...
"</body>\n\n" + ...
"<!-- Load dependencies from vendor/ -->\n" + ...
"<script src='vendor/d3.v5.9.2.min.js'></script>\n\n" + ...
"<!-- Load component files -->\n" + ...
"<script src='render.js'></script>\n" + ...
"<script src='main.js'></script>\n\n" + ...
"<script>\n" + ...
"    // Validate dependencies loaded\n" + ...
"    if (typeof d3 === 'undefined') {\n" + ...
"        console.error('[" + name + "] D3.js failed to load');\n" + ...
"    }\n" + ...
"</script>\n" + ...
"</html>\n"
];

template.css = [
"/* Component-specific styling for " + name + " */\n" + ...
"html, body {\n" + ...
"    margin: 0;\n" + ...
"    padding: 0;\n" + ...
"    width: 100%;\n" + ...
"    height: 100%;\n" + ...
"    overflow: hidden;\n" + ...
"}\n\n" + ...
"#root {\n" + ...
"    width: 100%;\n" + ...
"    height: 100%;\n" + ...
"}\n"
];

template.mainjs = [
"/* Bootstrap logic for " + name + " component */\n\n" + ...
"function setup(htmlComponent) {\n" + ...
"    console.log('[" + name + "] setup() called');\n" + ...
"    \n" + ...
"    try {\n" + ...
"        var data = htmlComponent.Data;\n" + ...
"        renderComponent(data, htmlComponent);\n" + ...
"        \n" + ...
"        htmlComponent.addEventListener('DataChanged', function(event) {\n" + ...
"            console.log('[" + name + "] DataChanged event received');\n" + ...
"            renderComponent(htmlComponent.Data, htmlComponent);\n" + ...
"        });\n" + ...
"        \n" + ...
"        console.log('[" + name + "] Setup complete');\n" + ...
"    } catch (error) {\n" + ...
"        console.error('[" + name + "] Error in setup():', error);\n" + ...
"    }\n" + ...
"}\n\n" + ...
"console.log('[" + name + "] Controller loaded');\n"
];

template.renderjs = [
"/* Rendering logic for " + name + " component */\n\n" + ...
"function renderComponent(data, htmlComponent) {\n" + ...
"    console.log('[" + name + "] renderComponent() called with data:', data);\n" + ...
"    \n" + ...
"    // Clear previous content\n" + ...
"    d3.select('#root').selectAll('*').remove();\n" + ...
"    \n" + ...
"    // Add your D3 visualization here\n" + ...
"    var svg = d3.select('#root')\n" + ...
"        .append('svg')\n" + ...
"        .attr('width', '100%')\n" + ...
"        .attr('height', '100%');\n" + ...
"    \n" + ...
"    svg.append('text')\n" + ...
"        .attr('x', '50%')\n" + ...
"        .attr('y', '50%')\n" + ...
"        .attr('text-anchor', 'middle')\n" + ...
"        .text('" + name + " Component');\n" + ...
"}\n\n" + ...
"console.log('[" + name + "] Renderer loaded');\n"
];

% Write all files
writeFile(files.m, template.m);
writeFile(files.readme, template.readme);
writeFile(files.html, template.html);
writeFile(files.css, template.css);
writeFile(files.mainjs, template.mainjs);
writeFile(files.renderjs, template.renderjs);
end

function matlabClass = createViewMatlabClass(name)
% Generate MATLAB class for VIEW (one-way data flow, no events/callbacks)
    matlabClass = [ ...
        "classdef " + name + " < matlab.ui.componentcontainer.ComponentContainer" + newline + ...
        "    % " + name + " - Observable Plot visualization view" + newline + ...
        "    % Version: 1.0.0" + newline + ...
        "    %" + newline + ...
        "    % This is a VIEW component (read-only, one-way data flow):" + newline + ...
        "    %   - No events" + newline + ...
        "    %   - No callbacks" + newline + ...
        "    %   - No bidirectional communication" + newline + ...
        "    %   - Pure data visualization" + newline + ...
        "    %" + newline + ...
        "    % View Structure:" + newline + ...
        "    %   - " + name + ".m: MATLAB class (this file)" + newline + ...
        "    %   - web/index.html: HTML entry point (UMD pattern)" + newline + ...
        "    %   - web/main.js: Simplified bootstrap (DataChanged only)" + newline + ...
        "    %   - web/render.js: Observable Plot v0.6.17 visualization" + newline + ...
        "    %   - web/styles.css: View-specific styles" + newline + ...
        "    %   - web/vendor/d3.min.js: D3.js (UMD build)" + newline + ...
        "    %   - web/vendor/plot.min.js: Observable Plot v0.6.17 (UMD build)" + newline + ...
        "    " + newline + ...
        "    properties" + newline + ...
        "        % Data to visualize" + newline + ...
        "        Data = []  % TODO: Add validation" + newline + ...
        "        " + newline + ...
        "        % TODO: Add display properties" + newline + ...
        "    end" + newline + ...
        "    " + newline + ...
        "    properties (Access = private, Transient, NonCopyable)" + newline + ...
        "        % Internal HTML component for rendering" + newline + ...
        "        HTMLComponent matlab.ui.control.HTML" + newline + ...
        "    end" + newline + ...
        "    " + newline + ...
        "    methods (Access = protected)" + newline + ...
        "        function setup(comp)" + newline + ...
        "            % Create HTML component and set source" + newline + ...
        "            comp.HTMLComponent = uihtml(comp);" + newline + ...
        "            comp.HTMLComponent.HTMLSource = " + name + ".resolveHTMLSource();" + newline + ...
        "            comp.HTMLComponent.Position = [1 1 comp.Position(3:4)];" + newline + ...
        "            " + newline + ...
        "            % Initial update" + newline + ...
        "            comp.update();" + newline + ...
        "        end" + newline + ...
        "        " + newline + ...
        "        function update(comp)" + newline + ...
        "            % Sync MATLAB properties to JavaScript" + newline + ...
        "            " + newline + ...
        "            % Prepare data structure for JavaScript" + newline + ...
        "            viewData = struct();" + newline + ...
        "            viewData.data = comp.Data;" + newline + ...
        "            % TODO: Add more properties" + newline + ...
        "            " + newline + ...
        "            % Send data to JavaScript (triggers DataChanged event in HTML)" + newline + ...
        "            comp.HTMLComponent.Data = viewData;" + newline + ...
        "            " + newline + ...
        "            % Update positioning" + newline + ...
        "            comp.HTMLComponent.Position = [1 1 comp.Position(3:4)];" + newline + ...
        "        end" + newline + ...
        "    end" + newline + ...
        "    " + newline + ...
        "    methods (Access = private, Static)" + newline + ...
        "        function htmlPath = resolveHTMLSource()" + newline + ...
        "            % Resolve path to index.html (works in dev and packaged toolbox)" + newline + ...
        "            classFile = mfilename('fullpath');" + newline + ...
        "            classDir = fileparts(classFile);" + newline + ...
        "            htmlPath = fullfile(classDir, 'web', 'index.html');" + newline + ...
        "        end" + newline + ...
        "    end" + newline + ...
        "end" + newline ...
    ];
end

function matlabClass = createComponentMatlabClass(name)
% Generate MATLAB class for COMPONENT (bidirectional, events/callbacks)
    matlabClass = [ ...
        "classdef " + name + " < matlab.ui.componentcontainer.ComponentContainer" + newline + ...
        "    % " + name + " - Interactive component" + newline + ...
        "    % Version: 1.0.0" + newline + ...
        "    " + newline + ...
        "    properties" + newline + ...
        "        Value = []  % TODO: Add validation" + newline + ...
        "    end" + newline + ...
        "    " + newline + ...
        "    properties (Access = private, Transient, NonCopyable)" + newline + ...
        "        HTMLComponent matlab.ui.control.HTML" + newline + ...
        "    end" + newline + ...
        "    " + newline + ...
        "    events (HasCallbackProperty, NotifyAccess = protected)" + newline + ...
        "        ValueChanged" + newline + ...
        "    end" + newline + ...
        "    " + newline + ...
        "    methods (Access = protected)" + newline + ...
        "        function setup(comp)" + newline + ...
        "            comp.HTMLComponent = uihtml(comp);" + newline + ...
        "            comp.HTMLComponent.HTMLSource = " + name + ".resolveHTMLSource();" + newline + ...
        "            comp.HTMLComponent.Position = [1 1 comp.Position(3:4)];" + newline + ...
        "            comp.HTMLComponent.HTMLEventReceivedFcn = @(src, evt) comp.handleEvent(evt);" + newline + ...
        "            comp.update();" + newline + ...
        "        end" + newline + ...
        "        " + newline + ...
        "        function update(comp)" + newline + ...
        "            if isempty(comp.HTMLComponent) || ~isvalid(comp.HTMLComponent)" + newline + ...
        "                return;" + newline + ...
        "            end" + newline + ...
        "            comp.HTMLComponent.Position = [1 1 comp.Position(3:4)];" + newline + ...
        "            comp.HTMLComponent.Data = struct('value', comp.Value);" + newline + ...
        "        end" + newline + ...
        "        " + newline + ...
        "        function handleEvent(comp, evt)" + newline + ...
        "            try" + newline + ...
        "                data = jsondecode(evt.HTMLEventData);" + newline + ...
        "                disp(['Event: ' evt.HTMLEventName]);" + newline + ...
        "                % TODO: Handle events and trigger callbacks" + newline + ...
        "            catch err" + newline + ...
        "                warning('Error handling event: %s', err.message);" + newline + ...
        "            end" + newline + ...
        "        end" + newline + ...
        "    end" + newline + ...
        "    " + newline + ...
        "    methods (Access = private, Static)" + newline + ...
        "        function htmlPath = resolveHTMLSource()" + newline + ...
        "            classFile = mfilename('fullpath');" + newline + ...
        "            classDir = fileparts(classFile);" + newline + ...
        "            htmlPath = fullfile(classDir, 'web', 'index.html');" + newline + ...
        "        end" + newline + ...
        "    end" + newline + ...
        "end" + newline ...
    ];
end

function matlabClass = createD3ComponentMatlabClass(name)
% Generate MATLAB class for D3 COMPONENT with throttled event handling
    matlabClass = [ ...
        "classdef " + name + " < matlab.ui.componentcontainer.ComponentContainer" + newline + ...
        "    % " + name + " - Interactive D3.js component" + newline + ...
        "    % Version: 1.0.0" + newline + ...
        "    %" + newline + ...
        "    % Component Structure:" + newline + ...
        "    %   - " + name + ".m: MATLAB class (this file)" + newline + ...
        "    %   - web/index.html: HTML entry point" + newline + ...
        "    %   - web/main.js: Controller (lifecycle and MATLAB communication)" + newline + ...
        "    %   - web/render.js: Renderer (D3 visualization logic)" + newline + ...
        "    %   - web/styles.css: Component styles" + newline + ...
        "    %   - web/vendor/d3.v5.9.2.min.js: Bundled D3.js dependency" + newline + ...
        "    " + newline + ...
        "    properties" + newline + ...
        "        Value = []  % TODO: Add validation and description" + newline + ...
        "        % TODO: Add more component properties" + newline + ...
        "    end" + newline + ...
        "    " + newline + ...
        "    properties (Access = private, Transient, NonCopyable)" + newline + ...
        "        HTMLComponent matlab.ui.control.HTML" + newline + ...
        "        ThrottleTimer  % For throttling rapid events" + newline + ...
        "        PendingData    % Store pending event data" + newline + ...
        "    end" + newline + ...
        "    " + newline + ...
        "    events (HasCallbackProperty, NotifyAccess = protected)" + newline + ...
        "        ValueChanged" + newline + ...
        "        % TODO: Add more events as needed" + newline + ...
        "    end" + newline + ...
        "    " + newline + ...
        "    methods (Access = protected)" + newline + ...
        "        function setup(comp)" + newline + ...
        "            comp.HTMLComponent = uihtml(comp);" + newline + ...
        "            comp.HTMLComponent.HTMLSource = " + name + ".resolveHTMLSource();" + newline + ...
        "            comp.HTMLComponent.Position = [1 1 comp.Position(3:4)];" + newline + ...
        "            comp.HTMLComponent.HTMLEventReceivedFcn = @(src, evt) comp.handleEvent(evt);" + newline + ...
        "            " + newline + ...
        "            % Initialize throttle timer for rapid events (optional)" + newline + ...
        "            comp.ThrottleTimer = timer(..." + newline + ...
        "                'ExecutionMode', 'singleShot', ..." + newline + ...
        "                'StartDelay', 0.05, ...  % 50ms throttle" + newline + ...
        "                'TimerFcn', @(~,~) comp.processPendingData());" + newline + ...
        "            " + newline + ...
        "            comp.update();" + newline + ...
        "        end" + newline + ...
        "        " + newline + ...
        "        function update(comp)" + newline + ...
        "            if isempty(comp.HTMLComponent) || ~isvalid(comp.HTMLComponent)" + newline + ...
        "                return;" + newline + ...
        "            end" + newline + ...
        "            comp.HTMLComponent.Position = [1 1 comp.Position(3:4)];" + newline + ...
        "            " + newline + ...
        "            % TODO: Build data structure for JavaScript" + newline + ...
        "            data = struct();" + newline + ...
        "            data.value = comp.Value;" + newline + ...
        "            comp.HTMLComponent.Data = data;" + newline + ...
        "        end" + newline + ...
        "        " + newline + ...
        "        function handleEvent(comp, evt)" + newline + ...
        "            try" + newline + ...
        "                eventName = evt.HTMLEventName;" + newline + ...
        "                " + newline + ...
        "                % Parse event data from CustomEvent detail" + newline + ...
        "                if ~isempty(evt.HTMLEventData)" + newline + ...
        "                    data = jsondecode(evt.HTMLEventData);" + newline + ...
        "                else" + newline + ...
        "                    data = struct();" + newline + ...
        "                end" + newline + ...
        "                " + newline + ...
        "                % TODO: Handle specific events" + newline + ...
        "                switch eventName" + newline + ...
        "                    case 'ValueChanged'" + newline + ...
        "                        disp(['[' eventName '] Event received']);" + newline + ...
        "                        notify(comp, 'ValueChanged');" + newline + ...
        "                        " + newline + ...
        "                    otherwise" + newline + ...
        "                        disp(['[' eventName '] Unhandled event']);" + newline + ...
        "                end" + newline + ...
        "            catch err" + newline + ...
        "                warning('[" + name + "] Error handling event: %s', err.message);" + newline + ...
        "            end" + newline + ...
        "        end" + newline + ...
        "        " + newline + ...
        "        function processPendingData(comp)" + newline + ...
        "            % Process throttled events (optional)" + newline + ...
        "            if ~isempty(comp.PendingData)" + newline + ...
        "                % TODO: Process pending data" + newline + ...
        "                comp.PendingData = [];" + newline + ...
        "            end" + newline + ...
        "        end" + newline + ...
        "    end" + newline + ...
        "    " + newline + ...
        "    methods (Access = private, Static)" + newline + ...
        "        function htmlPath = resolveHTMLSource()" + newline + ...
        "            classFile = mfilename('fullpath');" + newline + ...
        "            classDir = fileparts(classFile);" + newline + ...
        "            htmlPath = fullfile(classDir, 'web', 'index.html');" + newline + ...
        "        end" + newline + ...
        "    end" + newline + ...
        "end" + newline ...
    ];
end

function readme = createReadme(name, library, isView)
% Generate README content
    componentType = "View";
    if ~isView
        componentType = "Component";
    end
    
    readme = [ ...
        "# " + name + " " + componentType + newline + ...
        newline + ...
        "## Description" + newline + ...
        "[Add description of what this " + lower(componentType) + " does]" + newline + ...
        newline + ...
        "## Dependencies" + newline + ...
        "- " + library + " (UMD build)" + newline + ...
        "- D3.js (UMD build, bundled in web/vendor/)" + newline + ...
        newline + ...
        "## Usage" + newline + ...
        "```matlab" + newline + ...
        "fig = uifigure('Position', [100 100 800 600]);" + newline + ...
        "view = " + name + "(fig, 'Position', [50 50 700 500]);" + newline + ...
        "view.Data = yourData;" + newline + ...
        "```" + newline + ...
        newline + ...
        "## Properties" + newline + ...
        "- `Data` - [Add description]" + newline + ...
        newline + ...
        "## Implementation Notes" + newline + ...
        "- TODO: Implement Observable Plot visualization in web/render.js" + newline + ...
        "- TODO: Add appropriate properties in " + name + ".m" + newline + ...
        "- TODO: Update this README with actual usage examples" + newline ...
    ];
end

function writeFile(filepath, content)
    fid = fopen(filepath, 'w');
    fwrite(fid, content);
    fclose(fid);
end

function createObservablePlotComponent(name, base, webDir, vendorDir, isView)
% Create Observable Plot component/view from templates
    
    % Copy Observable Plot libraries to vendor directory
    libDir = fullfile(pwd, "lib", "observable-plot");
    copyfile(fullfile(libDir, "d3.min.js"), fullfile(vendorDir, "d3.min.js"));
    copyfile(fullfile(libDir, "plot.min.js"), fullfile(vendorDir, "plot.min.js"));
    
    % Read templates
    templateDir = fullfile(pwd, "utils", "templates", "observable-plot");
    
    % Placeholder replacements
    containerClass = lower(name) + "-container";
    renderFunction = "render" + name;
    
    % Read and process templates
    htmlTemplate = fileread(fullfile(templateDir, "index.html"));
    htmlTemplate = strrep(htmlTemplate, "{{COMPONENT_NAME}}", name);
    htmlTemplate = strrep(htmlTemplate, "{{CONTAINER_CLASS}}", containerClass);
    
    mainTemplate = fileread(fullfile(templateDir, "main.js"));
    mainTemplate = strrep(mainTemplate, "{{COMPONENT_NAME}}", name);
    mainTemplate = strrep(mainTemplate, "{{RENDER_FUNCTION}}", renderFunction);
    
    renderTemplate = fileread(fullfile(templateDir, "render.js"));
    renderTemplate = strrep(renderTemplate, "{{COMPONENT_NAME}}", name);
    renderTemplate = strrep(renderTemplate, "{{RENDER_FUNCTION}}", renderFunction);
    renderTemplate = strrep(renderTemplate, "{{CONTAINER_CLASS}}", containerClass);
    
    cssTemplate = fileread(fullfile(templateDir, "styles.css"));
    cssTemplate = strrep(cssTemplate, "{{COMPONENT_NAME}}", name);
    cssTemplate = strrep(cssTemplate, "{{CONTAINER_CLASS}}", containerClass);
    
    % Write web files
    writeFile(fullfile(webDir, "index.html"), htmlTemplate);
    writeFile(fullfile(webDir, "main.js"), mainTemplate);
    writeFile(fullfile(webDir, "render.js"), renderTemplate);
    writeFile(fullfile(webDir, "styles.css"), cssTemplate);
    
    % Create MATLAB class file
    if isView
        matlabClass = createViewMatlabClass(name);
    else
        matlabClass = createComponentMatlabClass(name);
    end
    writeFile(fullfile(base, name + ".m"), matlabClass);
    
    % Create README
    readmeContent = createReadme(name, "Observable Plot v0.6.17", isView);
    writeFile(fullfile(base, "README.md"), readmeContent);
end

function createD3Component(name, base, webDir, vendorDir, isView)
% Create D3.js component from templates
    
    % Copy D3.js library to vendor directory (same version as d3Brush)
    libDir = fullfile(pwd, "lib", "d3");
    d3File = "d3.v5.9.2.min.js";
    if isfile(fullfile(libDir, d3File))
        copyfile(fullfile(libDir, d3File), fullfile(vendorDir, d3File));
    else
        % Fallback: copy from d3Brush if lib/d3 doesn't exist
        d3BrushVendor = fullfile(pwd, "controllers", "@d3Brush", "web", "vendor", d3File);
        if isfile(d3BrushVendor)
            copyfile(d3BrushVendor, fullfile(vendorDir, d3File));
        else
            warning("D3.js library not found. Please manually add %s to %s", d3File, vendorDir);
        end
    end
    
    % Read templates
    templateDir = fullfile(pwd, "utils", "templates", "d3");
    
    % Placeholder replacements
    containerClass = lower(name) + "-container";
    renderFunction = "render" + name;
    
    % Read and process templates
    htmlTemplate = fileread(fullfile(templateDir, "index.html"));
    htmlTemplate = strrep(htmlTemplate, "{{COMPONENT_NAME}}", name);
    htmlTemplate = strrep(htmlTemplate, "{{CONTAINER_CLASS}}", containerClass);
    
    mainTemplate = fileread(fullfile(templateDir, "main.js"));
    mainTemplate = strrep(mainTemplate, "{{COMPONENT_NAME}}", name);
    mainTemplate = strrep(mainTemplate, "{{RENDER_FUNCTION}}", renderFunction);
    
    renderTemplate = fileread(fullfile(templateDir, "render.js"));
    renderTemplate = strrep(renderTemplate, "{{COMPONENT_NAME}}", name);
    renderTemplate = strrep(renderTemplate, "{{RENDER_FUNCTION}}", renderFunction);
    renderTemplate = strrep(renderTemplate, "{{CONTAINER_CLASS}}", containerClass);
    
    cssTemplate = fileread(fullfile(templateDir, "styles.css"));
    cssTemplate = strrep(cssTemplate, "{{COMPONENT_NAME}}", name);
    cssTemplate = strrep(cssTemplate, "{{CONTAINER_CLASS}}", containerClass);
    
    % Write web files
    writeFile(fullfile(webDir, "index.html"), htmlTemplate);
    writeFile(fullfile(webDir, "main.js"), mainTemplate);
    writeFile(fullfile(webDir, "render.js"), renderTemplate);
    writeFile(fullfile(webDir, "styles.css"), cssTemplate);
    
    % Create MATLAB class file
    if isView
        matlabClass = createViewMatlabClass(name);
    else
        matlabClass = createD3ComponentMatlabClass(name);
    end
    writeFile(fullfile(base, name + ".m"), matlabClass);
    
    % Create README
    readmeContent = createReadme(name, "D3.js v5.9.2", isView);
    writeFile(fullfile(base, "README.md"), readmeContent);
end

function generateTestFiles(name, libraryType, isView, testDataPath)
% Generate HTML and MATLAB test files for the component
    
    % Determine component path
    if isView
        componentPath = "views/@" + name;
        componentTypeStr = "view";
        componentTypeUpper = "VIEW";
    else
        componentPath = "controllers/@" + name;
        componentTypeStr = "controller";
        componentTypeUpper = "CONTROLLER";
    end
    
    % Create test directories if they don't exist
    htmlTestDir = fullfile(pwd, "tests", "html");
    matlabTestDir = fullfile(pwd, "tests", "matlab");
    if ~exist(htmlTestDir, "dir")
        mkdir(htmlTestDir);
    end
    if ~exist(matlabTestDir, "dir")
        mkdir(matlabTestDir);
    end
    
    % Determine which template to use
    if strcmpi(libraryType, 'observable-plot')
        templateDir = fullfile(pwd, "utils", "templates", "observable-plot");
        libraryScripts = [ ...
            "    <script src=""../../lib/observable-plot/d3.min.js""></script>" + newline + ...
            "    <script src=""../../lib/observable-plot/plot.min.js""></script>" ...
        ];
        libraryDescription = "Observable Plot v0.6.17 (UMD build)";
    elseif strcmpi(libraryType, 'd3')
        templateDir = fullfile(pwd, "utils", "templates", "d3");
        libraryScripts = "    <script src=""../../lib/d3/d3.v5.9.2.min.js""></script>";
        libraryDescription = "D3.js v5.9.2";
    else
        % Custom template - basic setup
        templateDir = fullfile(pwd, "utils", "templates", "d3");
        libraryScripts = "    <!-- TODO: Add library scripts -->";
        libraryDescription = "Custom libraries";
    end
    
    % Placeholder replacements
    containerClass = lower(name) + "-container";
    renderFunction = "render" + name;
    
    % Read and process HTML test template
    htmlTestTemplate = fileread(fullfile(templateDir, "test.html"));
    htmlTestTemplate = strrep(htmlTestTemplate, "{{COMPONENT_NAME}}", name);
    htmlTestTemplate = strrep(htmlTestTemplate, "{{COMPONENT_PATH}}", componentPath);
    htmlTestTemplate = strrep(htmlTestTemplate, "{{CONTAINER_CLASS}}", containerClass);
    htmlTestTemplate = strrep(htmlTestTemplate, "{{RENDER_FUNCTION}}", renderFunction);
    htmlTestTemplate = strrep(htmlTestTemplate, "{{LIBRARY_SCRIPTS}}", libraryScripts);
    
    % Add data loading code if test data path is provided
    if ~isempty(testDataPath)
        [~, ~, ext] = fileparts(testDataPath);
        if strcmpi(ext, '.csv')
            dataLoadCode = "        d3.csv('" + testDataPath + "', d3.autoType).then(function(data) {" + newline + ...
                          "            testData = data;" + newline + ...
                          "            runTests();" + newline + ...
                          "        });";
        elseif strcmpi(ext, '.tsv')
            dataLoadCode = "        d3.tsv('" + testDataPath + "', d3.autoType).then(function(data) {" + newline + ...
                          "            testData = data;" + newline + ...
                          "            runTests();" + newline + ...
                          "        });";
        elseif strcmpi(ext, '.json')
            dataLoadCode = "        d3.json('" + testDataPath + "').then(function(data) {" + newline + ...
                          "            testData = data;" + newline + ...
                          "            runTests();" + newline + ...
                          "        });";
        else
            dataLoadCode = "        // TODO: Add data loading code for " + testDataPath;
        end
        htmlTestTemplate = strrep(htmlTestTemplate, "        // TODO: Load test data", dataLoadCode);
    end
    
    % Read and process MATLAB test template
    matlabTestTemplate = fileread(fullfile(templateDir, "test.m"));
    matlabTestTemplate = strrep(matlabTestTemplate, "{{COMPONENT_NAME}}", name);
    matlabTestTemplate = strrep(matlabTestTemplate, "{{COMPONENT_TYPE}}", componentTypeStr);
    matlabTestTemplate = strrep(matlabTestTemplate, "{{COMPONENT_TYPE_UPPER}}", componentTypeUpper);
    matlabTestTemplate = strrep(matlabTestTemplate, "{{LIBRARY_DESCRIPTION}}", libraryDescription);
    
    % Add MATLAB data loading code if test data path is provided
    if ~isempty(testDataPath)
        [~, ~, ext] = fileparts(testDataPath);
        if strcmpi(ext, '.csv')
            matlabDataLoadCode = [ ...
                "dataPath = fullfile(fileparts(mfilename('fullpath')), '" + testDataPath + "');" + newline + ...
                "testData = readtable(dataPath);" ...
            ];
        elseif strcmpi(ext, '.tsv')
            matlabDataLoadCode = [ ...
                "dataPath = fullfile(fileparts(mfilename('fullpath')), '" + testDataPath + "');" + newline + ...
                "testData = readtable(dataPath, 'FileType', 'text', 'Delimiter', '\t');" ...
            ];
        else
            matlabDataLoadCode = [ ...
                "% TODO: Load test data from: " + testDataPath ...
            ];
        end
        matlabTestTemplate = strrep(matlabTestTemplate, "% TODO: Load or generate test data", matlabDataLoadCode);
    end
    
    % Write test files
    htmlTestPath = fullfile(htmlTestDir, "test_" + name + ".html");
    matlabTestPath = fullfile(matlabTestDir, "test_" + name + ".m");
    writeFile(htmlTestPath, htmlTestTemplate);
    writeFile(matlabTestPath, matlabTestTemplate);
    
    disp("Test files generated:");
    disp("  " + htmlTestPath);
    disp("  " + matlabTestPath);
end